# Версия docker-compose
version: '4.19.0'
# Список наших сервисов (контейнеров)
services:
    mysql:
        container_name: container_mysql_8.4
        image: mysql:8.4
        volumes:
#         - ./etc/mysql:/etc/mysql
         - ./logs/mysql:/var/log/mysql
         - ./mysql:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
#         - ./dump_arm_maket.sql:/docker-entrypoint-initdb.d/dump_arm_maket.sql
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - 3306:3306
    nginx1:
        container_name: container_nginx_1.27
        # используем последний стабильный образ nginx
        image: nginx:1.27
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
            - "755:755"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts/nginx.conf:/etc/nginx/nginx.conf
            - ./hosts/conf.d:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php555
            - php777
            - php888
    php888:
        container_name: container_php_8.3
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php8
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - ./logs/php:/var/log/php
            - ./php.ini:/usr/local/etc/php/php.ini
    php777:
        container_name: container_php_7.4
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php7
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - ./logs/php:/var/log/php
            - ./php.ini:/usr/local/etc/php/php.ini
    php555:
        container_name: container_php_5.4
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php5
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - ./logs/php:/var/log/php
            - ./php.ini:/usr/local/etc/php/php.ini

